name: s3_file_uploader

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Upload files to S3
        run: |
          aws s3 sync . s3://bannerserver-bucket-v1/preview-server \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".DS_Store" \
            --exclude "*.log"
